### ISSUE TITLE
Mobile responsiveness for the landing page

### ISSUE THREAD

**Issue by daluclemas** [badging/eventBadging#109] opened 2023-05-05 08:31 UTC
HI @kaxada , @Ruth-ikegah @iamkingsleey ,i'll like to work on making the landing page responsive if the design exists. if not and u want me to continue, i can do that as well

**Comment by tayyab-ilyas** [comment] 2023-05-07 15:37
anyone working on this? if not I'd like to

**Comment by daluclemas** [comment] 2023-05-07 16:33
> anyone working on this? if not I'd like to

Hi, i am

**Comment by Barry-dE** [comment] 2023-07-18 15:28
I'd love to join you guys to work on it  as well

**Comment by kaxada** [comment] 2023-10-03 13:08
duplicate of https://github.com/badging/badging/issues/80

**Closed as completed by kaxada** 2023-10-03 13:08 UTC
Labels: duplicate
